/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetozika.Pages.Perfil;

import Models.Usuario;
import Templates.BaseLayout;
import Utils.Navigation;
import Utils.Styles;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 * Tela de listagem do fornecedores
 * 
 * @author Welison
 */
public class Perfil extends Templates.BaseLayout {
    
    private BaseLayout self;
    public static JTable tabela;
    public static DefaultTableModel tableModel;
    private JButton btnEditar;

    /**
     * Cria a tela de fornecedores
     */
    public Perfil() {
        super();
        self = this;
        initComponents();
        createBaseLayout();
        addTopContent("Perfil");
        addCenterContent();
        addBottomContent();
    }
    
    // Adiciona conteúdo ao centro da area de conteúdo
    public void addCenterContent() {
        makeTable();
        JScrollPane barraRolagem = new JScrollPane(tabela);
        Styles.defaultScroll(barraRolagem);
        pCenter.add(barraRolagem, BorderLayout.CENTER);
    }
    
    /**
     * Gera a tabela com os dados
     */
    private void makeTable() {
        // cria tabela
        tabela = new JTable();
        tabela.setRowHeight(35);
        // seta colunas
        String[] colunas = {"", "Seus Dados"};
       // seta modelo
        Usuario u = new Usuario("22122-11","Welison Menezes","welison@email.com","9999-9999","2233-3322","Recursos Humanos","Masculino","Adminstrador","10/10/1998");
        Object[][] data = {
            {"Cpf",u.getCpf()},
            {"Nome", u.getNome()},
            {"Email", u.getEmail()},
            {"Celular", u.getCelular()},
            {"Telefone", u.getTelefone()},
            {"Setor", u.getSetor()},
            {"Sexo", u.getSexo()},
            {"Permissão", u.getPermissao()},
            {"Data de Nascimento", u.getData()}
        };
        tableModel = new DefaultTableModel(data, colunas) {
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
        // cria tabela
        tabela = new JTable(tableModel);
        tabela.setRowHeight(35);
        
    }
    
    /**
     * Adiciona o conteúdo à area de footer do conteúdo
     */
    public void addBottomContent() {
        btnEditar = new JButton("Editar Perfil");
        Styles.defaultButton(btnEditar);
        pBottom.add(btnEditar);
        btnEditar.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Navigation.updateLayout("editarPerfil", "11");
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 25, 50, 25));
        setMinimumSize(new java.awt.Dimension(1, 1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
