-- MySQL Script generated by MySQL Workbench
-- 03/19/19 19:49:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BANCO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BANCO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BANCO` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `BANCO` ;

-- -----------------------------------------------------
-- Table `BANCO`.`Banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BANCO`.`Banco` (
  `Codigo` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BANCO`.`Agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BANCO`.`Agencia` (
  `Numero` INT NOT NULL,
  `Endereco` VARCHAR(100) NULL,
  `BancoCodigo` INT NOT NULL,
  PRIMARY KEY (`Numero`),
  INDEX `fk_Agencia_Banco_idx` (`BancoCodigo` ASC),
  UNIQUE INDEX `Numero_UNIQUE` (`Numero` ASC),
  CONSTRAINT `fk_Agencia_Banco`
    FOREIGN KEY (`BancoCodigo`)
    REFERENCES `BANCO`.`Banco` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BANCO`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BANCO`.`Cliente` (
  `Cpf` BIGINT NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cpf`),
  UNIQUE INDEX `Cpf_UNIQUE` (`Cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BANCO`.`Conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BANCO`.`Conta` (
  `Numero` INT NOT NULL,
  `Saldo` DOUBLE NOT NULL,
  `TipoConta` VARCHAR(45) NOT NULL,
  `AgenciaNumero` INT NOT NULL,
  PRIMARY KEY (`Numero`),
  INDEX `fk_Conta_Agencia1_idx` (`AgenciaNumero` ASC),
  UNIQUE INDEX `Numero_UNIQUE` (`Numero` ASC),
  CONSTRAINT `fk_Conta_Agencia1`
    FOREIGN KEY (`AgenciaNumero`)
    REFERENCES `BANCO`.`Agencia` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BANCO`.`TelefoneCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BANCO`.`TelefoneCliente` (
  `Telefone` VARCHAR(20) NOT NULL,
  `ClienteCpf` BIGINT NOT NULL,
  INDEX `fk_TelefoneCliente_Cliente1_idx` (`ClienteCpf` ASC),
  CONSTRAINT `fk_TelefoneCliente_Cliente1`
    FOREIGN KEY (`ClienteCpf`)
    REFERENCES `BANCO`.`Cliente` (`Cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BANCO`.`Historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BANCO`.`Historico` (
  `ClienteCpf` BIGINT NOT NULL,
  `ContaNumero` INT NOT NULL,
  `DataInicio` DATETIME NULL,
  PRIMARY KEY (`ClienteCpf`, `ContaNumero`),
  INDEX `fk_Cliente_has_Conta_Conta1_idx` (`ContaNumero` ASC),
  INDEX `fk_Cliente_has_Conta_Cliente1_idx` (`ClienteCpf` ASC),
  CONSTRAINT `fk_Cliente_has_Conta_Cliente1`
    FOREIGN KEY (`ClienteCpf`)
    REFERENCES `BANCO`.`Cliente` (`Cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Conta_Conta1`
    FOREIGN KEY (`ContaNumero`)
    REFERENCES `BANCO`.`Conta` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
