/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetozika.Pages;

import Utils.Methods;
import java.util.Properties;

/**
 *
 * @author Welison
 */
public class Dashboard extends Templates.BaseLayout {
    
    /**
     * Creates new form Dashboard
     */
    public Dashboard(Properties params) {
        super();
        this.self = this;
        this.params = params;
        
        initComponents();
        createBaseLayout();
        
        translation();
    }
    
    private void translation() {
        addTopContent(Methods.getTranslation("Dashboard"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(37, 38, 39));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 25, 50, 25));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
