/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetozika.Pages;

import Utils.UtilsElements;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.JPanel;

/**
 *
 * @author Welison
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        System.out.println("projetozika.Pages.Login.<init>()");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fEmail1 = new javax.swing.JTextField();
        fEmail2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(37, 38, 39));
        setName("login"); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Senha");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(8, 253, 216));
        jButton1.setText("Entrar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(8, 253, 216)));
        jButton1.setContentAreaFilled(false);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Faça seu login");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        fEmail1.setBackground(new java.awt.Color(55, 57, 59));
        fEmail1.setForeground(new java.awt.Color(255, 255, 255));
        fEmail1.setCaretColor(new java.awt.Color(255, 255, 255));
        fEmail1.setOpaque(false);
        fEmail1.setPreferredSize(new java.awt.Dimension(200, 35));
        add(fEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 240, -1));

        fEmail2.setBackground(new java.awt.Color(55, 57, 59));
        fEmail2.setForeground(new java.awt.Color(255, 255, 255));
        fEmail2.setCaretColor(new java.awt.Color(255, 255, 255));
        fEmail2.setOpaque(false);
        fEmail2.setPreferredSize(new java.awt.Dimension(200, 35));
        add(fEmail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 240, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        UtilsElements.updateLayout("dashboard");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fEmail1;
    private javax.swing.JTextField fEmail2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
