/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetozika.Pages;

import Utils.UtilsElements;
import javax.swing.JFrame;
import projetozika.Login;
import projetozika.Main;

/**
 *
 * @author Welison
 */
public class Menu extends javax.swing.JPanel {
    
    Main main;
    /**
     * Creates new form Menu
     */
    public Menu(Main main) {
        initComponents();
        this.main = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNotasFiscais = new javax.swing.JLabel();
        lDashboard = new javax.swing.JLabel();
        lPerfil = new javax.swing.JLabel();
        lProdutos = new javax.swing.JLabel();
        lFornecedores = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lPedidos = new javax.swing.JLabel();
        lUsuarios = new javax.swing.JLabel();
        lRelatorios = new javax.swing.JLabel();

        setBackground(new java.awt.Color(24, 24, 24));
        setPreferredSize(new java.awt.Dimension(250, 50));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lNotasFiscais.setBackground(new java.awt.Color(7, 7, 7));
        lNotasFiscais.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lNotasFiscais.setForeground(new java.awt.Color(8, 253, 216));
        lNotasFiscais.setText("Notas Fiscais");
        lNotasFiscais.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        lNotasFiscais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lNotasFiscais.setOpaque(true);
        lNotasFiscais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lNotasFiscaisMouseClicked(evt);
            }
        });
        add(lNotasFiscais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 230, 30));

        lDashboard.setBackground(new java.awt.Color(7, 7, 7));
        lDashboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lDashboard.setForeground(new java.awt.Color(8, 253, 216));
        lDashboard.setText("Dashboard");
        lDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        lDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lDashboard.setOpaque(true);
        lDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lDashboardMouseClicked(evt);
            }
        });
        add(lDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, 30));

        lPerfil.setBackground(new java.awt.Color(7, 7, 7));
        lPerfil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lPerfil.setForeground(new java.awt.Color(8, 253, 216));
        lPerfil.setText("Perfil");
        lPerfil.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        lPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lPerfil.setOpaque(true);
        add(lPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 230, 30));

        lProdutos.setBackground(new java.awt.Color(7, 7, 7));
        lProdutos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lProdutos.setForeground(new java.awt.Color(8, 253, 216));
        lProdutos.setText("Produtos");
        lProdutos.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        lProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lProdutos.setOpaque(true);
        add(lProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 230, 30));

        lFornecedores.setBackground(new java.awt.Color(7, 7, 7));
        lFornecedores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lFornecedores.setForeground(new java.awt.Color(8, 253, 216));
        lFornecedores.setText("Fornecedores");
        lFornecedores.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        lFornecedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lFornecedores.setOpaque(true);
        lFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lFornecedoresMouseClicked(evt);
            }
        });
        add(lFornecedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 230, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("sair");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jButton1.setContentAreaFilled(false);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        lPedidos.setBackground(new java.awt.Color(7, 7, 7));
        lPedidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lPedidos.setForeground(new java.awt.Color(8, 253, 216));
        lPedidos.setText("Pedidos");
        lPedidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        lPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lPedidos.setOpaque(true);
        add(lPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 230, 30));

        lUsuarios.setBackground(new java.awt.Color(7, 7, 7));
        lUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lUsuarios.setForeground(new java.awt.Color(8, 253, 216));
        lUsuarios.setText("Usuários");
        lUsuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        lUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lUsuarios.setOpaque(true);
        add(lUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 230, 30));

        lRelatorios.setBackground(new java.awt.Color(7, 7, 7));
        lRelatorios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lRelatorios.setForeground(new java.awt.Color(8, 253, 216));
        lRelatorios.setText("Relatórios");
        lRelatorios.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        lRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lRelatorios.setOpaque(true);
        add(lRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 230, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //UtilsElements.updateLayout("login");
        this.main.dispose();
        JFrame login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lDashboardMouseClicked
        // TODO add your handling code here:
        UtilsElements.updateLayout("dashboard");
    }//GEN-LAST:event_lDashboardMouseClicked

    private void lFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lFornecedoresMouseClicked
        // TODO add your handling code here:
        UtilsElements.updateLayout("fornecedores");
    }//GEN-LAST:event_lFornecedoresMouseClicked

    private void lNotasFiscaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lNotasFiscaisMouseClicked
        // TODO add your handling code here:
        UtilsElements.updateLayout("notas");
    }//GEN-LAST:event_lNotasFiscaisMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lDashboard;
    private javax.swing.JLabel lFornecedores;
    private javax.swing.JLabel lNotasFiscais;
    private javax.swing.JLabel lPedidos;
    private javax.swing.JLabel lPerfil;
    private javax.swing.JLabel lProdutos;
    private javax.swing.JLabel lRelatorios;
    private javax.swing.JLabel lUsuarios;
    // End of variables declaration//GEN-END:variables
}
