/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetozika.Pages;

import Utils.Navigation;
import Utils.Styles;
import javax.swing.JFrame;
import projetozika.Login;
import projetozika.Main;

/**
 *
 * @author Welison
 */
public class Menu extends javax.swing.JPanel {
    
    Main main;
    /**
     * Creates new form Menu
     */
    public Menu(Main main) {
        initComponents();
        this.main = main;
        
        Styles.menuButton(bDashboard);
        Styles.menuButton(bFornecedores);
        Styles.menuButton(bNotasFiscais);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        bNotasFiscais = new javax.swing.JButton();
        bDashboard = new javax.swing.JButton();
        bFornecedores = new javax.swing.JButton();

        setBackground(new java.awt.Color(24, 24, 24));
        setPreferredSize(new java.awt.Dimension(250, 50));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("sair");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jButton1.setContentAreaFilled(false);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 40, 20));

        bNotasFiscais.setText("Notas Fiscais");
        bNotasFiscais.setName("notasFiscais"); // NOI18N
        bNotasFiscais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNotasFiscaisActionPerformed(evt);
            }
        });
        add(bNotasFiscais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        bDashboard.setText("Dashboard");
        bDashboard.setName("dashboard"); // NOI18N
        bDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDashboardActionPerformed(evt);
            }
        });
        add(bDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        bFornecedores.setText("Fornecedores");
        bFornecedores.setName("fornecedores"); // NOI18N
        bFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFornecedoresActionPerformed(evt);
            }
        });
        add(bFornecedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // logout
        this.main.dispose();
        JFrame login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bNotasFiscaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNotasFiscaisActionPerformed
        // TODO add your handling code here:
        //if (!evt.getComponent().isEnabled()) return;
        Navigation.updateLayout("notasFiscais");
    }//GEN-LAST:event_bNotasFiscaisActionPerformed

    private void bFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFornecedoresActionPerformed
        // TODO add your handling code here:
        Navigation.updateLayout("fornecedores");
    }//GEN-LAST:event_bFornecedoresActionPerformed

    private void bDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDashboardActionPerformed
        // TODO add your handling code here:
        Navigation.updateLayout("dashboard");
    }//GEN-LAST:event_bDashboardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDashboard;
    private javax.swing.JButton bFornecedores;
    private javax.swing.JButton bNotasFiscais;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
