package projetozika;

import Config.Environment;
import DAO.UsuarioDAO;
import Models.Usuario;
import Utils.AccessibilityManager;
import Utils.Navigation;
import Utils.Methods;
import Utils.Styles;
import java.awt.Toolkit;
import java.util.Properties;
import javax.swing.JFrame;

/**
 * Tela de login
 * @author Welison
 */
public class Configuracao extends JFrame {
    
    private final Properties params;

    /**
     * Creates new form Login
     */
    public Configuracao() {
        
        
        initComponents();
        this.params = new Properties();
        
        // add icon
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/sources/saturn.png")));
        
        // posiciona o frame na tela
        Methods.positionFrameInCenter(getInstance());
        
        // seta estilos aos elementos
        Styles.defaultButton(bentrar);
        Styles.defaultField(fhost);
        Styles.defaultField(fuser);
        Styles.defaultField(fsenha);
        
        // seta a acessibilidade
        AccessibilityManager.setAccessibility(getInstance());
        
        // Tradução
        translation();
    }
    
    /**
     * retorna a instância atual
     * @return a instância atual do JFrame
     */
    private JFrame getInstance() {
        return this;
    }
    
    /**
     * Resolve as traduções
     */
    private void translation() {
        ltitulo.setText(Methods.getTranslation("DadosConexao"));
        lsenha.setText(Methods.getTranslation("Senha"));
        lhost.setText(Methods.getTranslation("Host"));
        luser.setText(Methods.getTranslation("Usuario"));
        bentrar.setText(Methods.getTranslation("Entrar"));
        setTitle(Methods.getTranslation("ProjetoZika"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBg = new javax.swing.JPanel();
        ltitulo = new javax.swing.JLabel();
        lhost = new javax.swing.JLabel();
        fhost = new javax.swing.JTextField();
        lsenha = new javax.swing.JLabel();
        bentrar = new javax.swing.JButton();
        lInfo = new javax.swing.JLabel();
        fsenha = new javax.swing.JPasswordField();
        luser = new javax.swing.JLabel();
        fuser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(37, 38, 39));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBg.setBackground(new java.awt.Color(37, 38, 39));
        jBg.setPreferredSize(new java.awt.Dimension(400, 300));
        jBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ltitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ltitulo.setForeground(new java.awt.Color(255, 255, 255));
        ltitulo.setText("Dados da conexão");
        jBg.add(ltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        lhost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lhost.setForeground(new java.awt.Color(255, 255, 255));
        lhost.setText("Path");
        jBg.add(lhost, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 20));
        jBg.add(fhost, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 240, -1));

        lsenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lsenha.setForeground(new java.awt.Color(255, 255, 255));
        lsenha.setText("Senha");
        jBg.add(lsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, 20));

        bentrar.setText("Entrar");
        bentrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bentrarActionPerformed(evt);
            }
        });
        jBg.add(bentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 70, 30));

        lInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lInfo.setForeground(new java.awt.Color(255, 0, 0));
        jBg.add(lInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 160, 30));
        jBg.add(fsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 240, -1));

        luser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        luser.setForeground(new java.awt.Color(255, 255, 255));
        luser.setText("Usuário");
        jBg.add(luser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, 20));
        jBg.add(fuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 240, -1));

        getContentPane().add(jBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Escuta o evento de click do botão de login
     * @param evt o ActionEvent
     */
    private void bentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bentrarActionPerformed
        
        System.out.println("xxx");
   
    }//GEN-LAST:event_bentrarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Configuracao().setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bentrar;
    private javax.swing.JTextField fhost;
    private javax.swing.JPasswordField fsenha;
    private javax.swing.JTextField fuser;
    private javax.swing.JPanel jBg;
    private javax.swing.JLabel lInfo;
    private javax.swing.JLabel lhost;
    private javax.swing.JLabel lsenha;
    private javax.swing.JLabel ltitulo;
    private javax.swing.JLabel luser;
    // End of variables declaration//GEN-END:variables

}
