package projetozika;

import DAO.ConnectionFactory;
import Utils.AccessibilityManager;
import Utils.ConfigGenerator;
import Utils.Methods;
import Utils.Styles;
import Utils.Validator;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.util.Properties;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 * Tela de login
 * @author Welison
 */
public class Configuracao extends JFrame {
    
    private final Properties params;
    private final Login login;
    
    /**
     * Creates new form Login
     * @param login the Login JFrame
     */
    public Configuracao(Login login) {
        
       this.login = login;
       timerTest();
        
        initComponents();
        this.params = new Properties();
        
        // add icon
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/sources/saturn.png")));
        
        // posiciona o frame na tela
        Methods.positionFrameInCenter(getInstance());
        
        // seta estilos aos elementos
        Styles.defaultButton(bentrar);
        Styles.defaultField(fhost);
        Styles.defaultField(fuser);
        Styles.defaultField(fsenha);
        Styles.errorLabel(ehost);
        Styles.errorLabel(euser);
        Styles.errorLabel(epassword);
        
        // seta a acessibilidade
        AccessibilityManager.setAccessibility(getInstance());
        
        // Tradução
        translation();
        
        // reseta errors
        _resetaErrors();
        
        //ConfigGenerator configGenerator = new ConfigGenerator("host-enviado", "user-enviado", "password-enviado");
    }
    
    /**
     * retorna a instância atual
     * @return a instância atual do JFrame
     */
    private JFrame getInstance() {
        return this;
    }
    
    /**
     * Resolve as traduções
     */
    private void translation() {
        ltitulo.setText(Methods.getTranslation("DadosConexao"));
        lsenha.setText(Methods.getTranslation("Senha"));
        lhost.setText(Methods.getTranslation("Host"));
        luser.setText(Methods.getTranslation("Usuario"));
        bentrar.setText(Methods.getTranslation("Salvar"));
        setTitle(Methods.getTranslation("ProjetoZika"));
    }
    
    private void _resetaErrors() {
        ehost.setText("");
        euser.setText("");
        epassword.setText("");
    }
    
    private Timer t;
    private void timerTest() {
        
        t = new Timer(250, (ActionEvent e) -> {
            login.setVisible(false);
            t.stop();
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBg = new javax.swing.JPanel();
        ltitulo = new javax.swing.JLabel();
        lhost = new javax.swing.JLabel();
        fhost = new javax.swing.JTextField();
        lsenha = new javax.swing.JLabel();
        bentrar = new javax.swing.JButton();
        lInfo = new javax.swing.JLabel();
        fsenha = new javax.swing.JPasswordField();
        luser = new javax.swing.JLabel();
        fuser = new javax.swing.JTextField();
        epassword = new javax.swing.JLabel();
        ehost = new javax.swing.JLabel();
        euser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(37, 38, 39));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBg.setBackground(new java.awt.Color(37, 38, 39));
        jBg.setPreferredSize(new java.awt.Dimension(400, 300));
        jBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ltitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ltitulo.setForeground(new java.awt.Color(255, 255, 255));
        ltitulo.setText("Dados da conexão");
        jBg.add(ltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        lhost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lhost.setForeground(new java.awt.Color(255, 255, 255));
        lhost.setText("Path");
        jBg.add(lhost, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, 20));
        jBg.add(fhost, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 240, -1));

        lsenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lsenha.setForeground(new java.awt.Color(255, 255, 255));
        lsenha.setText("Senha");
        jBg.add(lsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 20));

        bentrar.setText("Salvar");
        bentrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bentrarActionPerformed(evt);
            }
        });
        jBg.add(bentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 70, 30));

        lInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lInfo.setForeground(new java.awt.Color(255, 0, 0));
        jBg.add(lInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 160, 30));
        jBg.add(fsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 240, -1));

        luser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        luser.setForeground(new java.awt.Color(255, 255, 255));
        luser.setText("Usuário");
        jBg.add(luser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 20));
        jBg.add(fuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 240, -1));

        epassword.setText("error");
        jBg.add(epassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        ehost.setText("error");
        jBg.add(ehost, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        euser.setText("error");
        jBg.add(euser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        getContentPane().add(jBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Escuta o evento de click do botão de login
     * @param evt o ActionEvent
     */
    private void bentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bentrarActionPerformed
        
        this._resetaErrors();
        // validação
        boolean isValid = true;
        if (! Validator.validaCampo(fhost, ehost, 1000)) isValid = false;
        //if (! Validator.validaCampo(fuser, euser, 1000)) isValid = false;
        //if (! Validator.validaCampo(fsenha, epassword, 1000)) isValid = false;
        if (isValid) {
            ConnectionFactory conTest = new ConnectionFactory();
            String password = new String(fsenha.getPassword()).trim();
            String host = fhost.getText().trim();
            String user = fuser.getText().trim();
            if (conTest.testConexao(host, user, password)) {
                ConfigGenerator configGenerator = new ConfigGenerator();
                configGenerator.createConfig(host, user, password);
                this.dispose();
                this.login.setVisible(true);
                this.login.buildPage();
            } else {
                JOptionPane.showMessageDialog(null, "Conexão falha");
            }
        }
    }//GEN-LAST:event_bentrarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bentrar;
    private javax.swing.JLabel ehost;
    private javax.swing.JLabel epassword;
    private javax.swing.JLabel euser;
    private javax.swing.JTextField fhost;
    private javax.swing.JPasswordField fsenha;
    private javax.swing.JTextField fuser;
    private javax.swing.JPanel jBg;
    private javax.swing.JLabel lInfo;
    private javax.swing.JLabel lhost;
    private javax.swing.JLabel lsenha;
    private javax.swing.JLabel ltitulo;
    private javax.swing.JLabel luser;
    // End of variables declaration//GEN-END:variables

}
