/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetozika.Pages.NotasFiscais;

import Templates.BaseLayout;

/**
 *
 * @author Welison
 */
public class NotasFiscais extends Templates.BaseLayout {
    
    BaseLayout self;
    
    /**
     * Creates new form NotasFiscais
     */
    public NotasFiscais() {
        super();
        self = this;
        initComponents();
        createBaseLayout();
        addTopContent("Notas Fiscais");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
