/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetozika.Pages.NotasFiscais;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Welison
 */
public class SelecionarProduto extends javax.swing.JPanel {

    /**
     * Creates new form SelecionarProduto
     */
    public SelecionarProduto() {
        initComponents();
        
        TitledBorder borderTitle = BorderFactory.createTitledBorder("Selecionar/Add Produto");
        borderTitle.setTitleColor(new Color(255, 255, 255));
        setBorder(borderTitle);
        setForeground(new Color(255, 102, 102));
        setBackground(new Color(37, 38, 39));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
