/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almoxerifado;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author sanvingla
 */
public class AddFornecedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddFornecedor
     */
    public AddFornecedor() {
        initComponents();
        FocosCor.ganharfocos(txtNomeFornecedor);
         FocosCor.ganharfocos(jFtCnpj);
         FocosCor.ganharfocos(jftTelefoneForn);
         
         //Util.setAccessibility(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAddFornecedor = new javax.swing.JLabel();
        jLabelNomeFornecedor = new javax.swing.JLabel();
        jLabelCnpjFornecedor = new javax.swing.JLabel();
        jLabelTelFornecedor = new javax.swing.JLabel();
        txtNomeFornecedor = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jFtCnpj = new javax.swing.JFormattedTextField();
        jftTelefoneForn = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();

        setTitle("Zika Sistemas");
        setPreferredSize(new java.awt.Dimension(800, 500));

        jLabelAddFornecedor.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabelAddFornecedor.setText("Add Fornecedor");

        jLabelNomeFornecedor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelNomeFornecedor.setText("Nome");

        jLabelCnpjFornecedor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelCnpjFornecedor.setText("CNPJ");

        jLabelTelFornecedor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelTelFornecedor.setText("Telefone");

        txtNomeFornecedor.setPreferredSize(new java.awt.Dimension(200, 28));
        txtNomeFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFornecedorActionPerformed(evt);
            }
        });
        txtNomeFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeFornecedorKeyTyped(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        try {
            jFtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFtCnpj.setMinimumSize(new java.awt.Dimension(200, 28));
        jFtCnpj.setPreferredSize(new java.awt.Dimension(200, 28));

        try {
            jftTelefoneForn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftTelefoneForn.setPreferredSize(new java.awt.Dimension(200, 28));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Status");

        txtStatus.setPreferredSize(new java.awt.Dimension(120, 28));
        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCnpjFornecedor)
                    .addComponent(jLabelTelFornecedor)
                    .addComponent(jLabelNomeFornecedor)
                    .addComponent(jLabelAddFornecedor)
                    .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFtCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jftTelefoneForn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(331, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(326, 326, 326))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabelAddFornecedor)
                .addGap(32, 32, 32)
                .addComponent(jLabelNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCnpjFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabelTelFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jftTelefoneForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFornecedorActionPerformed
         //TODO add your handling code here:
   //     int numeromax = 45;
     //    if(txtNomeFornecedor.getText().length() >= numeromax){
       //   evt.consume();
         // JOptionPane.showMessageDialog(txtNomeFornecedor, "maximo 45 caracteres");
     // }
    }//GEN-LAST:event_txtNomeFornecedorActionPerformed

    private void txtNomeFornecedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFornecedorKeyTyped
//        // TODO add your handling code here:
         int numeromax = 45;
      if(txtNomeFornecedor.getText().length() >= numeromax){
          evt.consume();
          JOptionPane.showMessageDialog(txtNomeFornecedor, "maximo 45 caracteres");
      }
        
    }//GEN-LAST:event_txtNomeFornecedorKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        //conectar bd
        Conexao c = new Conexao();
        try {
            c.conectarBanco();

            // salvar
            c.operacaoDados("insert into fornecedor  (Nome, Cnpj, Telefone, Status) values ('" + txtNomeFornecedor.getText() + "','" + jFtCnpj.getText() 
                    + "','" + jftTelefoneForn.getText() + "','" + txtStatus.getText() + "')");

            //desconectar bds
            c.desconectarBanco();

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } catch (ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
        } catch (InstantiationException ex) {
            System.out.println(ex.getMessage());
        } catch (IllegalAccessException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JFormattedTextField jFtCnpj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAddFornecedor;
    private javax.swing.JLabel jLabelCnpjFornecedor;
    private javax.swing.JLabel jLabelNomeFornecedor;
    private javax.swing.JLabel jLabelTelFornecedor;
    private javax.swing.JFormattedTextField jftTelefoneForn;
    private javax.swing.JTextField txtNomeFornecedor;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
