/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almoxerifado;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanvingla
 */
public class ListarUsuario extends javax.swing.JFrame {
    
    String permissao = "";
    
    /**
     * Creates new form ListarUsuario
     */
    public ListarUsuario() {
        initComponents();
        listarUsuarios();
        
        if (!UsuarioLogado.getPermissao().equals("Administrador")) {
            btnRelatorio.setVisible(false);
        }
    }

    public void listarUsuarios() {
        try {
            DefaultTableModel dtmMarca = (DefaultTableModel) jTableUsuario.getModel();
            Conexao bd = new Conexao();
            dtmMarca.setRowCount(0);

            bd.conectarBanco();

            String sql = "select * from usuario";
            if (!permissao.equals("")) {
                sql +=  " where Permissao='" + this.permissao + "'";
            }
            
            bd.fazerConsulta(sql);

            while (bd.resultado.next()) {
                String campos[] = {bd.resultado.getInt("idusuario") + "", bd.resultado.getString("Cpf"), bd.resultado.getString("Senha"), bd.resultado.getString("Permissao"),
                    bd.resultado.getString("Telefone"), bd.resultado.getString("Celular"), bd.resultado.getString("setor"), bd.resultado.getString("Email"),
                     bd.resultado.getString("Sexo"), bd.resultado.getString("Nome"), bd.resultado.getString("Datadenascimento"), bd.resultado.getString("Status")};
                dtmMarca.addRow(campos);
            }
            bd.desconectarBanco();
        } catch (Exception exc) {
            System.out.println(exc.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPermissoes = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Listar Usuário");

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cpf", "senha", "Permissão", "Telefone", "Celular", "Setor", "Email", "Sexo", "Nome", "Data de Nascimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableUsuario);

        jLabel2.setText("Filtrar por permissão:");

        jPermissoes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Almoxarife", "Usuario" }));

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnRelatorio.setText("Gerar Relatório");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(178, 178, 178)
                .addComponent(btnRelatorio)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPermissoes, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnFiltrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jPermissoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar)
                    .addComponent(btnRelatorio))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        this.permissao = this.jPermissoes.getSelectedItem().toString();
        listarUsuarios();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
        ArrayList<String[]> dados = new ArrayList();
       
       int totalLinhas = jTableUsuario.getRowCount();
       for(int linha = 0; linha < totalLinhas; linha++) {
           String row[] = {
               jTableUsuario.getValueAt(linha, 0).toString(),
               jTableUsuario.getValueAt(linha, 1).toString(),
               jTableUsuario.getValueAt(linha, 3).toString(),
               jTableUsuario.getValueAt(linha, 4).toString(),
               jTableUsuario.getValueAt(linha, 5).toString(),
               jTableUsuario.getValueAt(linha, 6).toString(),
               jTableUsuario.getValueAt(linha, 7).toString(),
               jTableUsuario.getValueAt(linha, 8).toString(),
               jTableUsuario.getValueAt(linha, 9).toString(),
               jTableUsuario.getValueAt(linha, 10).toString()
           };
           dados.add(row);
       }
       
       String cabeca[] = {
           "ID",
           "CPF",
           "Permissão",
           "Telefone",
           "Celular",
           "Setor",
           "Email",
           "Sexo",
           "Nome",
           "Data"
       };
       String info[] = {};
       
        ReportModel repo = new ReportModel("relatorio-usuarios.pdf", "titulo.pdf", cabeca, info, dados);
        PDFGenerator pdf = new PDFGenerator(repo);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jPermissoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuario;
    // End of variables declaration//GEN-END:variables
}
