/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almoxerifado;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanvingla
 */
public class ListarFornecedores extends javax.swing.JInternalFrame {
    
    private String nomeFiltro = "";
    /**
     * Creates new form ListarFornecedores
     */
    public ListarFornecedores() {
        initComponents();
        listarFornecedores();
        
        if (!UsuarioLogado.getPermissao().equals("Administrador")) {
            btnRelatorio.setVisible(false);
        }
    }

    public void listarFornecedores() {
        try {
            DefaultTableModel dtmMarca = (DefaultTableModel) jTablefornecedor.getModel();
            Conexao bd = new Conexao();
            dtmMarca.setRowCount(0);

            bd.conectarBanco();

            String sql = "select * from fornecedor";
            
            if (!nomeFiltro.equals("")) {
                sql += " where Nome like '%"+ this.nomeFiltro +"%'";
            }
            
            bd.fazerConsulta(sql);

            while (bd.resultado.next()) {
                String campos[] = {bd.resultado.getInt("idfornecedor") + "", bd.resultado.getString("Nome"), bd.resultado.getString("Cnpj"), bd.resultado.getString("telefone")};
                dtmMarca.addRow(campos);
            }
            bd.desconectarBanco();
        } catch (Exception exc) {
            System.out.println(exc.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablefornecedor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jNome = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();

        jTablefornecedor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTablefornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idfornecedor", "Nome", "CNPJ", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTablefornecedor.setPreferredSize(new java.awt.Dimension(700, 300));
        jScrollPane1.setViewportView(jTablefornecedor);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("almoxerifado/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("ListarFornecedores.jLabel1.text")); // NOI18N

        jLabel2.setText(bundle.getString("ListarFornecedores.jLabel2.text")); // NOI18N

        jNome.setText(bundle.getString("ListarFornecedores.jNome.text")); // NOI18N

        btnFiltrar.setText(bundle.getString("ListarFornecedores.btnFiltrar.text")); // NOI18N
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnRelatorio.setText(bundle.getString("ListarFornecedores.btnRelatorio.text")); // NOI18N
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRelatorio))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFiltrar)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnRelatorio))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        this.nomeFiltro = this.jNome.getText();
        listarFornecedores();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
        ArrayList<String[]> dados = new ArrayList();
       
       int totalLinhas = jTablefornecedor.getRowCount();
       for(int linha = 0; linha < totalLinhas; linha++) {
           String row[] = {
               jTablefornecedor.getValueAt(linha, 0).toString(),
               jTablefornecedor.getValueAt(linha, 1).toString(),
               jTablefornecedor.getValueAt(linha, 2).toString(),
               jTablefornecedor.getValueAt(linha, 3).toString()
               
           };
           dados.add(row);
       }
       
       String cabeca[] = {
           "ID Fornecedor",
           "Nome",
           "CNPJ",
           "Telefone"
       };
       String info[] = {};
       
        ReportModel repo = new ReportModel("relatorio-fornecedores.pdf", "titulo.pdf", cabeca, info, dados);
        PDFGenerator pdf = new PDFGenerator(repo);
    }//GEN-LAST:event_btnRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablefornecedor;
    // End of variables declaration//GEN-END:variables
}
