/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almoxerifado;

import com.sun.glass.events.KeyEvent;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.util.HashSet;
import javax.swing.JFrame;

/**
 *
 * @author sanvingla
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public static MenuPrincipal FramePrincipal;
    public MenuPrincipal() {
        initComponents();
       Fechando.windowClosing(this);
        
        FramePrincipal = this;
        TrocaTabPorEnter(this);
        //Util.setAccessibility(this);
        Acelerador.Acelerador(this);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
	setVisible(false);
}
            }
        });

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanelTela = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItemCadastro = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuFornecedor = new javax.swing.JMenu();
        jMenuItemAddFornecedor = new javax.swing.JMenuItem();
        jMenuItemListarFornecedores = new javax.swing.JMenuItem();
        jMenuNotas = new javax.swing.JMenu();
        jMenuItemNotas = new javax.swing.JMenuItem();
        jMenuDados = new javax.swing.JMenu();
        jMenuItemDados = new javax.swing.JMenuItem();
        jMenuProdutos = new javax.swing.JMenu();
        jMenuItemProdutos = new javax.swing.JMenuItem();
        jMenuPedidos = new javax.swing.JMenu();
        jMenuItemPedido = new javax.swing.JMenuItem();
        jMenuItemSeusPed = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanelTela.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanelTela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanelTelaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTelaLayout = new javax.swing.GroupLayout(jPanelTela);
        jPanelTela.setLayout(jPanelTelaLayout);
        jPanelTelaLayout.setHorizontalGroup(
            jPanelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanelTelaLayout.setVerticalGroup(
            jPanelTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        jMenuUsuario.setText("Usuário");
        jMenuUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuUsuario.setPreferredSize(new java.awt.Dimension(100, 30));

        jMenuItemCadastro.setText("Cadastro");
        jMenuItemCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemCadastro);

        jMenuItem1.setText("Listar Usuário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItem1);

        jMenuBar1.add(jMenuUsuario);

        jMenuRelatorio.setText("Relatório");
        jMenuRelatorio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuRelatorio.setPreferredSize(new java.awt.Dimension(100, 30));
        jMenuBar1.add(jMenuRelatorio);

        jMenuFornecedor.setText("Fornecedores");
        jMenuFornecedor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuFornecedor.setPreferredSize(new java.awt.Dimension(130, 30));
        jMenuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFornecedorActionPerformed(evt);
            }
        });

        jMenuItemAddFornecedor.setText("Add Fornecedor");
        jMenuItemAddFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddFornecedorActionPerformed(evt);
            }
        });
        jMenuFornecedor.add(jMenuItemAddFornecedor);

        jMenuItemListarFornecedores.setText("Listar Fornecedores");
        jMenuItemListarFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarFornecedoresActionPerformed(evt);
            }
        });
        jMenuFornecedor.add(jMenuItemListarFornecedores);

        jMenuBar1.add(jMenuFornecedor);

        jMenuNotas.setText("Notas Fiscais");
        jMenuNotas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuNotas.setPreferredSize(new java.awt.Dimension(130, 30));

        jMenuItemNotas.setText("Notas");
        jMenuItemNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNotasActionPerformed(evt);
            }
        });
        jMenuNotas.add(jMenuItemNotas);

        jMenuBar1.add(jMenuNotas);

        jMenuDados.setText("Seus Dados");
        jMenuDados.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuDados.setPreferredSize(new java.awt.Dimension(120, 30));

        jMenuItemDados.setText("Meus Dados");
        jMenuItemDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDadosActionPerformed(evt);
            }
        });
        jMenuDados.add(jMenuItemDados);

        jMenuBar1.add(jMenuDados);

        jMenuProdutos.setText("Produtos");
        jMenuProdutos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuProdutos.setPreferredSize(new java.awt.Dimension(100, 30));

        jMenuItemProdutos.setText("Buscar Produtos");
        jMenuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutosActionPerformed(evt);
            }
        });
        jMenuProdutos.add(jMenuItemProdutos);

        jMenuBar1.add(jMenuProdutos);

        jMenuPedidos.setText("Pedidos");
        jMenuPedidos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuPedidos.setPreferredSize(new java.awt.Dimension(100, 30));

        jMenuItemPedido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItemPedido.setText("Pedidos");
        jMenuItemPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPedidoActionPerformed(evt);
            }
        });
        jMenuPedidos.add(jMenuItemPedido);

        jMenuItemSeusPed.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItemSeusPed.setText("Fazer pedidos");
        jMenuItemSeusPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSeusPedActionPerformed(evt);
            }
        });
        jMenuPedidos.add(jMenuItemSeusPed);

        jMenuBar1.add(jMenuPedidos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTela, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTela, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    private void jMenuItemCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroActionPerformed
        // TODO add your handling code here:
        jPanelTela.removeAll();
        jPanelTela.revalidate();
        CadastrarUsuario cadastrar = new CadastrarUsuario();
        jPanelTela.add(cadastrar);
        cadastrar.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemCadastroActionPerformed

    private void jMenuItemAddFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddFornecedorActionPerformed
        // TODO add your handling code here:
        jPanelTela.removeAll();
        jPanelTela.revalidate();
        AddFornecedor fornecedor  = new AddFornecedor();
        jPanelTela.add(fornecedor);
        fornecedor.setVisible(true);
    }//GEN-LAST:event_jMenuItemAddFornecedorActionPerformed

    private void jMenuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFornecedorActionPerformed

    }//GEN-LAST:event_jMenuFornecedorActionPerformed

    private void jMenuItemListarFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarFornecedoresActionPerformed
        // TODO add your handling code here:
        jPanelTela.removeAll();
        jPanelTela.revalidate();
        ListarFornecedores fornece = new ListarFornecedores();
        jPanelTela.add(fornece);
        fornece.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarFornecedoresActionPerformed

    private void jMenuItemNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNotasActionPerformed
        // TODO add your handling code here:
        jPanelTela.removeAll();
        jPanelTela.revalidate();
        Notas na = new Notas();
        jPanelTela.add(na);
        na.setVisible(true);
    }//GEN-LAST:event_jMenuItemNotasActionPerformed

    private void jPanelTelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanelTelaKeyPressed
        // TODO add your handling code here:
 
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
             setVisible(false); 
        }

    }//GEN-LAST:event_jPanelTelaKeyPressed

    private void jMenuItemPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPedidoActionPerformed
        // TODO add your handling code here:
        jPanelTela.removeAll();
        jPanelTela.revalidate();
        listarPedido Pe = new listarPedido();
        jPanelTela.add(Pe);
        Pe.setVisible(true);
    }//GEN-LAST:event_jMenuItemPedidoActionPerformed

    private void jMenuItemDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDadosActionPerformed
        // TODO add your handling code here:
        jPanelTela.removeAll();
        jPanelTela.revalidate();
        SeusDados dd = new SeusDados();
        jPanelTela.add(dd);
        dd.setVisible(true);
    }//GEN-LAST:event_jMenuItemDadosActionPerformed

    private void jMenuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutosActionPerformed
        // TODO add your handling code here:
        jPanelTela.removeAll();
        jPanelTela.revalidate();
        Produtos pd = new Produtos();
        jPanelTela.add(pd);
        pd.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemProdutosActionPerformed

    private void jMenuItemSeusPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSeusPedActionPerformed
        // TODO add your handling code here:
        jPanelTela.removeAll();
        jPanelTela.revalidate();
        SeuPedidos ped = new SeuPedidos ();
        jPanelTela.add(ped);
        ped.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemSeusPedActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ListarUsuario Li = new ListarUsuario();
        Li.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    
    static void TrocaTabPorEnter(JFrame frame ){
	HashSet conj = new HashSet(frame.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
	conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
	frame.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);		
}
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    public javax.swing.JMenu jMenuDados;
    public javax.swing.JMenu jMenuFornecedor;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAddFornecedor;
    private javax.swing.JMenuItem jMenuItemCadastro;
    private javax.swing.JMenuItem jMenuItemDados;
    private javax.swing.JMenuItem jMenuItemListarFornecedores;
    private javax.swing.JMenuItem jMenuItemNotas;
    public javax.swing.JMenuItem jMenuItemPedido;
    private javax.swing.JMenuItem jMenuItemProdutos;
    private javax.swing.JMenuItem jMenuItemSeusPed;
    public javax.swing.JMenu jMenuNotas;
    public javax.swing.JMenu jMenuPedidos;
    public javax.swing.JMenu jMenuProdutos;
    public javax.swing.JMenu jMenuRelatorio;
    public javax.swing.JMenu jMenuUsuario;
    public static javax.swing.JPanel jPanelTela;
    // End of variables declaration//GEN-END:variables

    private void Fechando(MenuPrincipal aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
