/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almoxerifado;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanvingla
 */
public class Notas extends javax.swing.JInternalFrame {
    private String fData = "";
    /**
     * Creates new form Notas
     */
    public Notas() {
        initComponents();
        listarNotas();
        
        if (!UsuarioLogado.getPermissao().equals("Administrador")) {
            btnRelatorio.setVisible(false);
        }
    }
    
    private void listarNotas() {
        try {
            DefaultTableModel dtmMarca = (DefaultTableModel) jTableAddNotas.getModel();
            Conexao bd = new Conexao();
            dtmMarca.setRowCount(0);

            bd.conectarBanco();

            String sql = "select * from `nota fiscal` inner join fornecedor on idfornecedor = fornecedor_idfornecedor";
           
            if (!this.fData.equals("")) {
                sql += " where DatadeEmissao >= '"+ this.fData +"'";
            }
            
            bd.fazerConsulta(sql);

            while (bd.resultado.next()) {
                String campos[] = {bd.resultado.getString("fornecedor.nome") + "", bd.resultado.getString("cnpj"), bd.resultado.getString("idfornecedor"),
                    bd.resultado.getString("NumeroDaNota"), bd.resultado.getString("NumeroDeSerie"), bd.resultado.getString("valornota"),
                    bd.resultado.getString("DatadeEmissao")};
                dtmMarca.addRow(campos);
            }
            bd.desconectarBanco();
        } catch (Exception exc) {
            System.out.println(exc.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAddNotas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        jTestDatadenascimento = new javax.swing.JFormattedTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        btnRelatorio = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 500));

        jTableAddNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cnpj", "Id", "Numero da nota", "Numero de Serie", "Valor", "Data"
            }
        ));
        jScrollPane1.setViewportView(jTableAddNotas);

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Adicionar Novo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Notas Fiscais");

        jLabel2.setText("Filtrar por data");

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        try {
            jTestDatadenascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTestDatadenascimento.setPreferredSize(new java.awt.Dimension(100, 28));
        jTestDatadenascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTestDatadenascimentoKeyPressed(evt);
            }
        });

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnRelatorio.setText("Gerar Relatório");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRelatorio)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFiltrar)
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(322, 322, 322)
                    .addComponent(jTestDatadenascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(322, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButton1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnFiltrar)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(223, 223, 223)
                    .addComponent(jTestDatadenascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(224, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        AddNotas nt = new AddNotas(this);
        nt.setVisible(true);
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTestDatadenascimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTestDatadenascimentoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTestDatadenascimentoKeyPressed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        this.fData = jFormattedTextField1.getText();
        listarNotas();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
        ArrayList<String[]> dados = new ArrayList();
       
       int totalLinhas = jTableAddNotas.getRowCount();
       for(int linha = 0; linha < totalLinhas; linha++) {
           String row[] = {
               jTableAddNotas.getValueAt(linha, 0).toString(),
               jTableAddNotas.getValueAt(linha, 1).toString(),
               jTableAddNotas.getValueAt(linha, 2).toString(),
               jTableAddNotas.getValueAt(linha, 3).toString(),
               jTableAddNotas.getValueAt(linha, 4).toString(),
               jTableAddNotas.getValueAt(linha, 5).toString(),
               jTableAddNotas.getValueAt(linha, 6).toString()
           };
           dados.add(row);
       }
       
       String cabeca[] = {
           "Nome",
           "CNPJ",
           "ID",
           "Nº Nota",
           "Nº Série",
           "Valor",
           "Data"
       };
       String info[] = {};
       
        ReportModel repo = new ReportModel("relatorio-notas.pdf", "titulo.pdf", cabeca, info, dados);
        PDFGenerator pdf = new PDFGenerator(repo);
    }//GEN-LAST:event_btnRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableAddNotas;
    private javax.swing.JFormattedTextField jTestDatadenascimento;
    // End of variables declaration//GEN-END:variables
}
