/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almoxerifado;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanvingla
 */
public class Produtos extends javax.swing.JInternalFrame {
    
    private String fUnidades = "";
    
    /**
     * Creates new form AddProdutos
     */
    public Produtos() {
        initComponents();
        listarProdutos();
        
        if (!UsuarioLogado.getPermissao().equals("Administrador")) {
            btnRelatorio.setVisible(false);
        }
    }
    
    private void listarProdutos() {
        try {
            DefaultTableModel dtmMarca = (DefaultTableModel) jTableprodutos.getModel();
            Conexao bd = new Conexao();
            dtmMarca.setRowCount(0);

            bd.conectarBanco();

            String sql = "select * from produto where Status = 1";
            
            if (!this.fUnidades.equals("")) {
                sql += " and unidade = '"+ this.fUnidades +"'";
            }
            
            bd.fazerConsulta(sql);

            while (bd.resultado.next()) {
                String campos[] = {bd.resultado.getInt("idproduto") + "", bd.resultado.getString("Nome"), bd.resultado.getString("unidade"), bd.resultado.getString("Status")};
                dtmMarca.addRow(campos);
            }
            bd.desconectarBanco();
        } catch (Exception exc) {
            System.out.println(exc.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableprodutos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jUnidades = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();

        setTitle("Zika Sistemas");

        jTableprodutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idproduto", "Nome", "unidade", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTableprodutos);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Produtos");

        jUnidades.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jUnidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "unidade", "litros", "pacote", "caixa" }));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton1.setText("Adicionar Novo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel1.setText("Filtrar por unidade:");

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnRelatorio.setText("Gerar Relatório");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRelatorio)
                        .addGap(41, 41, 41)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFiltrar)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnEditar)
                    .addComponent(jButton1)
                    .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnFiltrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        AddProdutos ap = new AddProdutos();
        ap.setVisible(true);
    }//GEN-LAST:event_jButton1MousePressed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int linhaprod = jTableprodutos.getSelectedRow();
        if (linhaprod != -1) {
            int idproduto = Integer.parseInt(jTableprodutos.getValueAt(linhaprod, 0).toString());

            new AddProdutos(idproduto).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "seleciona o produto!");
        }


    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        this.fUnidades = jUnidades.getSelectedItem().toString();
        listarProdutos();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
        ArrayList<String[]> dados = new ArrayList();
       
       int totalLinhas = jTableprodutos.getRowCount();
       for(int linha = 0; linha < totalLinhas; linha++) {
           String row[] = {
               jTableprodutos.getValueAt(linha, 0).toString(),
               jTableprodutos.getValueAt(linha, 1).toString(),
               jTableprodutos.getValueAt(linha, 2).toString(),
               jTableprodutos.getValueAt(linha, 3).toString()
           };
           dados.add(row);
       }
       
       String cabeca[] = {
           "ID Produto",
           "Nome",
           "Unidade",
           "Status"
       };
       String info[] = {};
       
        ReportModel repo = new ReportModel("relatorio-produtos.pdf", "titulo.pdf", cabeca, info, dados);
        PDFGenerator pdf = new PDFGenerator(repo);
    }//GEN-LAST:event_btnRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableprodutos;
    private javax.swing.JComboBox<String> jUnidades;
    // End of variables declaration//GEN-END:variables
}
