/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almoxerifado;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanvingla
 */
public class Requisitar extends javax.swing.JFrame {

    Conexao bd = new Conexao();
    Requisitar self;
    private int idprod;
    private int idPedido = 0;

    /**
     * Creates new form Requisitar
     */
    public Requisitar() {
        initComponents();
        self = this;
    }
    
    public Requisitar(String idPedido, String status) {
        initComponents();
        self = this;
        this.idPedido = Integer.parseInt(idPedido);
        if(this.idPedido > 0) {
            pegaItensPedido();
        }
        if (!status.equals("Pendente")) {
            jButton1.setVisible(false);
            btnBuscar.setVisible(false);
            btnEnviarPed.setVisible(false);
        }
    }
    
    public void pegaItensPedido() {
        try {
            DefaultTableModel dtmMarca = (DefaultTableModel) jTableRequisitar.getModel();
            Conexao bd = new Conexao();
            dtmMarca.setRowCount(0);

            bd.conectarBanco();

            String sql = "select * from itens_pedidos left join produto on produto.idproduto=itens_pedidos.id_produtos where id_pedidos = " + idPedido;
            bd.fazerConsulta(sql);

            while (bd.resultado.next()) {
                String campos[] = {
                    bd.resultado.getInt("produto.idproduto") + "", 
                    bd.resultado.getString("produto.Nome"), 
                    bd.resultado.getString("produto.unidade"), 
                    bd.resultado.getString("itens_pedidos.quantidade_solicitada")};
                dtmMarca.addRow(campos);
            }
            bd.desconectarBanco();
        } catch (Exception exc) {
            System.out.println(exc.getMessage());
        }

    }
    
    public void criarPedido() {
        int idpedido = 0;
        int idusuario = UsuarioLogado.getId();
        try {
            String sql = "insert into pedidos (DataSolicitacao, Status, usuario) values ( (select now()),'Pendente', " + idusuario + " )";
            
            bd.conectarBanco();
            idpedido = bd.operacaoDados(sql);
            bd.desconectarBanco();
            
        } catch (Exception exc) {
            System.out.println(exc.getMessage());
        }
        
        criarItensPedido(idpedido);
    }
    
    public void criarItensPedido(int idpedido) {
        if (idpedido > 0) {

            int linhas = jTableRequisitar.getRowCount();
            for (int row = 0; row < linhas; row++) {
                try {
                    int idproduto = Integer.parseInt(jTableRequisitar.getValueAt(row, 0).toString());
                    int quantidade = Integer.parseInt(jTableRequisitar.getValueAt(row, 3).toString());
                    String sql = "insert into itens_pedidos (id_pedidos, id_produtos, quantidade_solicitada) values (" + idpedido + ", " + idproduto + ", "+quantidade+")";
                    
                    bd.conectarBanco();
                    bd.operacaoDados(sql);
                    bd.desconectarBanco();
                    
                } catch (Exception exc) {
                    System.out.println(exc.getMessage());
                }

            }
            this.dispose();
            
            if(this.idPedido > 0) {
                JOptionPane.showMessageDialog(null, "Pedido editado com sucesso.");
            } else {
                JOptionPane.showMessageDialog(null, "Pedido criado com sucesso.");
            }
        }
    }
    
    public void editarPedido() {
        try {
            String sql = "delete from itens_pedidos where id_pedidos = " + this.idPedido;
            
            bd.conectarBanco();
            bd.operacaoDados(sql);
            bd.desconectarBanco();
            
        } catch (Exception exc) {
            System.out.println(exc.getMessage());
        }
        
        criarItensPedido(this.idPedido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRequisitar = new javax.swing.JTable();
        btnEnviarPed = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setTitle("Zika Sistemas");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Requisitando produto");

        jTableRequisitar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Unidade", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(jTableRequisitar);

        btnEnviarPed.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEnviarPed.setText("Enviar Pedido");
        btnEnviarPed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarPedMouseClicked(evt);
            }
        });
        btnEnviarPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarPedActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar Produto");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jButton1.setText("Remover Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEnviarPed)
                        .addGap(76, 76, 76)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscar)
                    .addComponent(jButton1))
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnviarPed, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarPedActionPerformed
        if(this.idPedido > 0) {
            editarPedido();
        } else {
            criarPedido();
        }
    }//GEN-LAST:event_btnEnviarPedActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        BuscarProdPed nx = new BuscarProdPed(bd, self);
        nx.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEnviarPedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarPedMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnEnviarPedMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int linha = jTableRequisitar.getSelectedRow();
        if (linha > -1) {
            ((DefaultTableModel)jTableRequisitar.getModel()).removeRow(linha);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um item.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Requisitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Requisitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Requisitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Requisitar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Requisitar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEnviarPed;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableRequisitar;
    // End of variables declaration//GEN-END:variables
}
