-- MySQL Script generated by MySQL Workbench
-- Wed Apr 17 12:07:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProjetoZika
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProjetoZika
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjetoZika` DEFAULT CHARACTER SET utf8 ;
USE `ProjetoZika` ;

-- -----------------------------------------------------
-- Table `ProjetoZika`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoZika`.`Usuarios` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(11) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Sexo` VARCHAR(10) NOT NULL,
  `Email` VARCHAR(100) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Celular` VARCHAR(45) NULL,
  `DataNascimento` DATE NOT NULL,
  `Setor` VARCHAR(45) NOT NULL,
  `Permissao` VARCHAR(45) NOT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(100) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Created` DATETIME NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) ,
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoZika`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoZika`.`Produtos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Unidade` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(255) NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Created` DATETIME NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoZika`.`Fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoZika`.`Fornecedores` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Cnpj` VARCHAR(14) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Telefone` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Created` DATETIME NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Cnpj_UNIQUE` (`Cnpj` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoZika`.`NotasFiscais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoZika`.`NotasFiscais` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Numero` BIGINT NOT NULL,
  `Serie` INT NOT NULL,
  `Valor` DOUBLE NOT NULL,
  `Data` DATETIME NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Created` DATETIME NOT NULL,
  `FornecedorId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_NotasFiscais_Fornecedores_idx` (`FornecedorId` ASC) ,
  CONSTRAINT `fk_NotasFiscais_Fornecedores`
    FOREIGN KEY (`FornecedorId`)
    REFERENCES `ProjetoZika`.`Fornecedores` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoZika`.`NotasFiscaisProdutos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoZika`.`NotasFiscaisProdutos` (
  `NotaFiscalId` INT NOT NULL,
  `ProdutoId` INT NOT NULL,
  `Valor` DOUBLE NOT NULL,
  `Quantidade` INT NOT NULL,
  `Created` DATETIME NOT NULL,
  PRIMARY KEY (`NotaFiscalId`, `ProdutoId`),
  INDEX `fk_NotasFiscais_has_Produtos_Produtos1_idx` (`ProdutoId` ASC) ,
  INDEX `fk_NotasFiscais_has_Produtos_NotasFiscais1_idx` (`NotaFiscalId` ASC) ,
  CONSTRAINT `fk_NotasFiscais_has_Produtos_NotasFiscais1`
    FOREIGN KEY (`NotaFiscalId`)
    REFERENCES `ProjetoZika`.`NotasFiscais` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NotasFiscais_has_Produtos_Produtos1`
    FOREIGN KEY (`ProdutoId`)
    REFERENCES `ProjetoZika`.`Produtos` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoZika`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoZika`.`Estoque` (
  `ProdutoId` INT NOT NULL,
  `Total` INT NOT NULL,
  INDEX `fk_Estoque_Produtos1_idx` (`ProdutoId` ASC) ,
  CONSTRAINT `fk_Estoque_Produtos1`
    FOREIGN KEY (`ProdutoId`)
    REFERENCES `ProjetoZika`.`Produtos` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoZika`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoZika`.`Pedidos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(45) NOT NULL,
  `Created` DATETIME NOT NULL,
  `UsuarioId` INT NOT NULL,
  `AlmoxarifeId` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Pedidos_Usuarios1_idx` (`UsuarioId` ASC) ,
  CONSTRAINT `fk_Pedidos_Usuarios1`
    FOREIGN KEY (`UsuarioId`)
    REFERENCES `ProjetoZika`.`Usuarios` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoZika`.`PedidosProdutos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoZika`.`PedidosProdutos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `PedidoId` INT NOT NULL,
  `ProdutoId` INT NOT NULL,
  `QuantidadeSolicitada` INT NOT NULL,
  `QuantidadeAprovada` INT NULL,
  PRIMARY KEY (`Id`, `PedidoId`, `ProdutoId`),
  INDEX `fk_Pedidos_has_Produtos_Produtos1_idx` (`ProdutoId` ASC) ,
  INDEX `fk_Pedidos_has_Produtos_Pedidos1_idx` (`PedidoId` ASC) ,
  CONSTRAINT `fk_Pedidos_has_Produtos_Pedidos1`
    FOREIGN KEY (`PedidoId`)
    REFERENCES `ProjetoZika`.`Pedidos` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_has_Produtos_Produtos1`
    FOREIGN KEY (`ProdutoId`)
    REFERENCES `ProjetoZika`.`Produtos` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
