package projetozika.Pages.Relatorios;

import Templates.BaseLayout;
import Utils.AccessibilityManager;
import Utils.Methods;
import java.awt.BorderLayout;
import java.util.Properties;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 * Tela de listagem do fornecedores
 * @author Welison
 */
public class Relatorios extends BaseLayout {

    private JTabbedPane jTabbedPane1;
    private JPanel panelPedidos;
    private JPanel panelProdutos;

    /**
     * Cria a tela de fornecedores
     * @param params Parâmetros para filtro e paginação
     */
    public Relatorios(Properties params) {
        super();
        this.self = getInstance();
        this.params = params;
        
        initComponents();
        createBaseLayout();
        addCenterContent();
    }
    
    /**
     * Adiciona conteúdo ao centro da area de conteúdo
     */
    private void addCenterContent() {
        jTabbedPane1 = new JTabbedPane();
        jTabbedPane1.setOpaque(false);
        
        panelPedidos = new RelatorioPedidos();
        panelProdutos = new RelatorioProdutos();
        
        jTabbedPane1.addTab(Methods.getTranslation("Pedidos"), panelPedidos);
        jTabbedPane1.addTab(Methods.getTranslation("Produtos"), panelProdutos);
        
        AccessibilityManager.setupTabTraversalKeys(jTabbedPane1);

        pCenter.add(jTabbedPane1, BorderLayout.CENTER);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 25, 50, 25));
        setMinimumSize(new java.awt.Dimension(1, 1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
