-- MySQL Script generated by MySQL Workbench
-- Fri Apr 26 12:17:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`alunos` (
  `MAT` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MAT`),
  UNIQUE INDEX `MAT_UNIQUE` (`MAT` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`disciplinas` (
  `COD_DISC` VARCHAR(10) NOT NULL,
  `nome_disc` VARCHAR(45) NOT NULL,
  `carga_hor` INT NOT NULL,
  PRIMARY KEY (`COD_DISC`),
  UNIQUE INDEX `COD_DISC_UNIQUE` (`COD_DISC` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`professores` (
  `COD_PROF` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COD_PROF`),
  UNIQUE INDEX `MAT_UNIQUE` (`COD_PROF` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`turma` (
  `COD_DISC` VARCHAR(10) NOT NULL,
  `COD_TURMA` INT NOT NULL,
  `COD_PROF` INT NOT NULL,
  `ano` INT NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COD_TURMA`, `COD_PROF`, `COD_DISC`),
  INDEX `fk_turma_professores1_idx` (`COD_PROF` ASC) ,
  INDEX `fk_turma_disciplinas1_idx` (`COD_DISC` ASC) ,
  CONSTRAINT `fk_turma_professores1`
    FOREIGN KEY (`COD_PROF`)
    REFERENCES `test`.`professores` (`COD_PROF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_disciplinas1`
    FOREIGN KEY (`COD_DISC`)
    REFERENCES `test`.`disciplinas` (`COD_DISC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`historico` (
  `MAT` INT NOT NULL,
  `COD_DISC` VARCHAR(10) NOT NULL,
  `COD_TURMA` INT NOT NULL,
  `COD_PROF` INT NOT NULL,
  `ano` INT NOT NULL,
  `frequencia` INT NOT NULL,
  `nota` DOUBLE NOT NULL,
  INDEX `fk_historico_alunos1_idx` (`MAT` ASC) ,
  INDEX `fk_historico_turma2_idx` (`COD_TURMA` ASC, `COD_PROF` ASC, `COD_DISC` ASC) ,
  CONSTRAINT `fk_historico_alunos1`
    FOREIGN KEY (`MAT`)
    REFERENCES `test`.`alunos` (`MAT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_turma2`
    FOREIGN KEY (`COD_TURMA` , `COD_PROF` , `COD_DISC`)
    REFERENCES `test`.`turma` (`COD_TURMA` , `COD_PROF` , `COD_DISC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
