/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetozika.Pages.Relatorios;

import Templates.BaseLayout;
import Templates.ComboItem;
import Templates.SuggestionsBox;
import Utils.Dialogs;
import Utils.Styles;
import com.toedter.calendar.JDateChooser;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
/**
 * Tela de listagem do fornecedores
 * 
 * @author Welison
 */
public class Relatorios extends Templates.BaseLayout {
    
    private BaseLayout self;
    public static JTable tabela;
    public static DefaultTableModel tableModel;
    private JTabbedPane jTabbedPane1;
    private JPanel panelPedidos;
    private JPanel panelProdutos;
    private JTextField fproduto;
    private JComboBox cproduto;
    private JLabel lproduto;
    private JPanel sproduto;
    private JLabel ldatafrom;
    private JDateChooser fdatafrom;
    private JLabel ldatato;
    private JDateChooser fdatato;
    private JLabel lusuario;
    private JTextField fusuario;
    private JPanel susuario;
    private JComboBox cusuario;
    private JButton btnRelatorioPedido;
    private JLabel edatafrom;
    private JLabel edatato;

    /**
     * Cria a tela de fornecedores
     */
    public Relatorios() {
        super();
        self = this;
        initComponents();
        createBaseLayout();
        //addTopContent("Relatórios");
        addCenterContent();
    }
    
    // Adiciona conteúdo ao centro da area de conteúdo
    public void addCenterContent() {
        jTabbedPane1 = new JTabbedPane();
        jTabbedPane1.setOpaque(false);
        
        panelPedidos = new RelatorioPedidos();
        panelProdutos = new RelatorioProdutos();
        
        jTabbedPane1.addTab("Pedidos", panelPedidos);
        jTabbedPane1.addTab("Produtos", panelProdutos);

        pCenter.add(jTabbedPane1, BorderLayout.CENTER);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 25, 50, 25));
        setMinimumSize(new java.awt.Dimension(1, 1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
